### ISSUE TITLE
iOS >10.1.1

### ISSUE THREAD

**Issue by CTKRocks** [EthanRDoesMC/Gandalf#13]
Why doesn't the tweak have 10.1.1 support? Luca's Jailbreak has support for iOS 10.1.1 and based on the simplicity of the package, I don't see why it can't support 10.1.1.

**Comment by EthanRDoesMC** [comment]
Gandalf is a tweak list. It's optimized for 10.2 (at the moment). Will support 10.1.1 soon.

**Comment by CTKRocks** [comment]
Got it. Still don't see why such a simple tweak isn't optimized.

**Comment by EthanRDoesMC** [comment]
Plan is to do it today. For example, under NO circumstances should you install OpenSHH on 10.2, but you absolutely should on 10.1.1. That's my biggest example.

**Comment by EthanRDoesMC** [comment]
I'll reopen the issue until there's a 10.1.1 version.

**Comment by CTKRocks** [comment]
Got it.

**Comment by EthanRDoesMC** [comment]
I'm working on it yay!

**Comment by EthanRDoesMC** [comment]
closing as reorg of folders makes it kind of obvious there's work being done on GandalfMach
