### ISSUE TITLE
2.0 beta2 

### ISSUE THREAD

**Issue by hcarrega** [EthanRDoesMC/Gandalf#17]
In this update Gandalf wont show to update

**Comment by EthanRDoesMC** [comment]
It shouldn't be. I fixed it but it still won't block. I'm beginning to blame Cydia on this one.

**Comment by EthanRDoesMC** [comment]
Update: asked Saurik for suggestions, he recommended I try Pinning Gandalf. It's a dpkg setting that prevents a package from being installed, uninstalled and/or updated based on prioritization. I'm thinking of incorporating this via Manager or a post-installation script (which is ALSO a thing) but leaning toward Manager as Gandalf needs to update and I have no idea how I'd automatically unpin it. In manager I can incorporate a button!


Hopefully that'll block packages. I'll go try it right now. If it does, we'll be back on track!
