### ISSUE TITLE
Add the version to the deb name

### ISSUE THREAD

**Issue by mehulrao** [EthanRDoesMC/Gandalf#18]
That way it is easier to know if the DEB is up-to-date with the current release.

**Comment by EthanRDoesMC** [comment]
Will do starting with Beta 3.

**Comment by mehulrao** [comment]
Ok. Will close this

**Comment by EthanRDoesMC** [comment]
No no no no!

If it's closed I'll forget about it!

**Comment by mehulrao** [comment]
Alright! is there any way to contact you directly?

**Comment by EthanRDoesMC** [comment]
I mean I've got a twitter @ethanrdoesmc_

**Comment by mehulrao** [comment]
Yeah, but i don't. Just PM me on Reddit. /u/mehulrao
