### ISSUE TITLE
Can't install 2.0-Delta2

### ISSUE THREAD

**Issue by xXDjMikeXx** [EthanRDoesMC/Gandalf#21]
Cydia gives me error message

**Comment by EthanRDoesMC** [comment]
wow, that didn't take long!

yeah, we know. 

so, apparently, what we were using to do a thing doesn't work because you can't drive a car if someone else is driving.

**Comment by xXDjMikeXx** [comment]
![](http://i.imgur.com/IzUyerU.jpg)

**Comment by mehulrao** [comment]
Whats the error?

**Comment by mehulrao** [comment]
Oh, I know the issue! Sorry abt that

**Comment by EthanRDoesMC** [comment]
So, um, can someone build it for me? I don't want to boot up my Linux VM _again_. I have the script fixed. Even turned it into a bash script (in a moment).

**Comment by EthanRDoesMC** [comment]
Ok, the new pin.sh is my temporary solution! YAAAAAY

**Comment by EthanRDoesMC** [comment]
also, hi CyDown

**Comment by xXDjMikeXx** [comment]
Okay?

**Comment by EthanRDoesMC** [comment]
pet peeves

don't ask

**Comment by xXDjMikeXx** [comment]
Okay😅

**Comment by EthanRDoesMC** [comment]
im so weird
