### ISSUE TITLE
I'm not bullshitting

### ISSUE THREAD

**Issue by nerdtron123** [EthanRDoesMC/gandalf#30]
I'm not bullshitting, put the tweak on a test device, or in a disassembler, it's an old tweak that doesn't bootloop, and many people had it installed, even check hashes, not my fault a karma whore released that post without proof of the bootloops.

**Comment by nerdtron123** [comment]
Friend me on discord

**Comment by EthanRDoesMC** [comment]
still blocking for the masses. Let the fire die out. Once that happens, I'll do some research. Got plenty of old devices.

**Comment by EthanRDoesMC** [comment]
Confirmed. You aren't. CoolStar has checked. Will be removed from Gandalf once proven OKAY.

**Comment by coolstar** [comment]
@EthanRDoesMC yes I have disassembled Priority Hub (version 2.2; deb SHA1: 5dd6b8b1bbaff9f4b38455b057b8a529c3145933) and have not found any malware. Looks like the people who posted on /r/jailbreak never actually tested it.

That being said, I can't guarantee that the package on the repo won't be malicious in the future. However, as long as the SHA1 of the deb on the repo matches the one I posted here, you should be safe.
