### ISSUE TITLE
packagedepiction wrong link

### ISSUE THREAD

**Issue by jonisc** [EthanRDoesMC/gandalf#37]
Hi Ethan,
the link to the info.xml has changed. now there`s a 404 in your repo.
I think it should be https://ethanrdoesmc.github.io/repo/depictions/io.github.ethanrdoesmc.gandalf102/info.xml?

**Comment by jonisc** [comment]
Fixed by @1Conan

**Comment by jonisc** [comment]
Fixed by @1Conan

**Comment by 1Conan** [comment]
#36 fixes this along with some refactoring of code

**Comment by EthanRDoesMC** [comment]
moving to new link, please change to ethanrdoesmc.github.io/gandalf/depictions/?p=io.github.ethanrdoesmc.gandalf102

**Comment by jonisc** [comment]
It's not a pr. So you must change it. But please don't do it now (might get conflicts with 1conan's PR? Don't know...

**Comment by mehulrao** [comment]
I'm on osx so maybe that's it @jonisc @1Conan @EthanRDoesMC

**Comment by jonisc** [comment]
I think you have commented to the wrong issue? Please comment to the PR.

**Comment by EthanRDoesMC** [comment]
lol

ill do the site change thing. was putting down solution so that i could do it on my ipad tonight if needed.
