### ISSUE TITLE
Name the hold script "gandalf" without version

### ISSUE THREAD

**Issue by jonisc** [EthanRDoesMC/gandalf#39]
So currently the script is called "gandalf102" maybe it's better if it's called "gandalf" only. So you don't have to rename it every time you create a new package.

**Comment by EthanRDoesMC** [comment]
That'll be easy, I'll do it tomorrow (today? I run off of EST no matter where I am. It's how I think.)

**Comment by 1Conan** [comment]
You can do this without "hacks" like `sed` in the build.sh. You can grep the correct package name during runtime :3

**Comment by jonisc** [comment]
Yep. You can do that, but it's easier if there's only one script for all versions it's much easier for the user + developer (e.g. then mehulrao doesn't have to edit the app every time)

**Comment by 1Conan** [comment]
@jonisc sorry for the lack of details in the message. I actually meant using something like `grep` to get a package name then holding it.

This is for making the gandalf command compatible with any version of the package.

Check the new branch I made. I won't open a PR for now since it's not tested. I don't have a JBed device to test on how does the commands behave on iOS. (Unless you can let me SSH in one of your devices :3 )

**Comment by jonisc** [comment]
Let you ssh into my device... If I had 2... could you please send me a compiled version (I am away from my pc).

**Comment by 1Conan** [comment]
A "compiled" version isn't needed. I just need to test some commands to check how the commands behave in the iOS ecosystem.

I've written the command string according to how it works in linux. But not everything is portable between linux and iOS. (Evem other *NIX-based OS)

**Comment by jonisc** [comment]
Ok. Could you please send the commands you want to test to me and I'll record my screen. I'll contact you if you have added an e-mail to your profile.

**Comment by jonisc** [comment]
Ok. You haven't. bananianx@t-online.de my "fake" e-mail

**Comment by 1Conan** [comment]
If you check the commit, you'll see the modifications I've made.
Basically, I need the output after running these commands.

```bash
dpkg-query -f '${binary:Package}\n' -W
dpkg-query -f '${binary:Package}\n' -W | grep io.github.ethanrdoesmc.gandalf
dpkg-query -f '${binary:Package}\n' -W | grep io.github.ethanrdoesmc.gandalf | head -n 1
```
The first one is needed to see if dpkg accepts the same parameters as the version I use on my Debian server.
The second one is to check whether grep will work the same way as on my server. 
Third one is to check whether `head` is available by default and functions the same.

I expect things to work as this isn't complicated.

**Comment by jonisc** [comment]
Just sent you a mail.

**Comment by 1Conan** [comment]
Didn't receive anything.

**Comment by jonisc** [comment]
Strange. [so than here's the link](https://splice.gopro.com/v?id=72reMo)

**Comment by 1Conan** [comment]
Then the modifications I made should work.

**Comment by jonisc** [comment]
Just thought so. You are sure that you have received my mail?

Am 6. Mai 2017, 23:25 +0200 schrieb 1Conan <notifications@github.com>:

**Comment by 1Conan** [comment]
It just arrived a few minutes ago in my spam mailbox

**Comment by jonisc** [comment]
Ok. Maybe because my email provider is unknown and has a .de

**Comment by 1Conan** [comment]
>outlook

There's the reason

**Comment by jonisc** [comment]
Ergh. Just realized that I have sent it from the "wrong" account (I have an other account from a local provider). But outlook.com is a "semi" well known provider since it's from Microsoft.

**Comment by 1Conan** [comment]
Ik that it is from microsoft.

There has been multiple problems regarding microsoft emails though.

I know a lot of occurances where they went straight to spam most of the
time.

**Comment by mehulrao** [comment]
Done
