### ISSUE TITLE
Gandalf app is crashing

### ISSUE THREAD

**Issue by jonisc** [EthanRDoesMC/gandalf#41]
Maybe use an old version. 
@mehulrao maybe open source it?

**Comment by mehulrao** [comment]
I already open sourced it. It's on my account. Use the .xcworkspace

**Comment by mehulrao** [comment]
Also, it works for me... Are you on the latest version?

**Comment by EthanRDoesMC** [comment]
I will do some investebugging

**Comment by EthanRDoesMC** [comment]
@jonisc are you having the problem too?

**Comment by jonisc** [comment]
Yep. It's crashing on launch while if I compile it via my Mac & install it everything works.

**Comment by mehulrao** [comment]
Fixed in latest Version

**Comment by jonisc** [comment]
Can confirm: it works.
