### ISSUE TITLE
Instead of `sleep` use read for y/ n

### ISSUE THREAD

**Issue by 1Conan** [EthanRDoesMC/gandalf#43]
Much better solution imho.

Also, 'confirming' isn't really needed as well. If you want to recreate the package without updating the version, you can just delete the deb file.

**Comment by jonisc** [comment]
Best thing would also be a timeout which automatically proceeds if there's no input. There's a very full featured example here: http://m.linuxjournal.com/content/asking-yesno-question-bash-script

**Comment by 1Conan** [comment]
That is simply an overkill solution. I suggest that we don't clutter the code with anymore unneeded stuff.

I recommended this because you want a "verification". This solution is much better imho.

**Comment by jonisc** [comment]
@1Conan: I think it's done now. Can we close this issue?
