### ISSUE TITLE
Gandalf on old repo removes new repo in case of remove

### ISSUE THREAD

**Issue by jonisc** [EthanRDoesMC/gandalf#44]
Problem: installing Gandalf from old repo and then removing it will delete the new repo. [VIDEO](https://splice.gopro.com/v?id=6KjmyY). 
The problem is that you should directly edit cydia.list in postinst. 

`#!/bin/bash

GANDALF_NEW_SRC=$(cat /etc/apt/sources.list.d/cydia.list | grep 'deb https://ethanrdoesmc.github.io/gandalf')

if [ "${GANDALF_NEW_SRC}" = "deb https://ethanrdoesmc.github.io/gandalf/ ./" ]; then

echo "New repo already added. Nothing to be done."
exit 
else
echo "Adding new repo..."

echo 'deb https://ethanrdoesmc.github.io/gandalf/ ./' >> /etc/apt/sources.list.d/cydia.list
apt-get update
echo "Thanks for using Gandalf. Please install Gandalf from the new repo from now one. You can delete this package now."

fi`
Current problem: after a refresh of sources the repo is gone.

**Comment by EthanRDoesMC** [comment]
Problem - good luck removing it like that. 

It should SHOULD be fixed

**Comment by EthanRDoesMC** [comment]
I'll try - the only reason I have the new one is through the new package.

**Comment by EthanRDoesMC** [comment]
Wait

**Comment by EthanRDoesMC** [comment]
Try it again

**Comment by jonisc** [comment]
Didn't work. After removing Gandalf from you old repo your new repo disappears -> maybe copy gandalf.list in postinst

**Comment by EthanRDoesMC** [comment]
Oh, that's intended.... if you're removing Gandalf, you probably don't want the repo.

**Comment by jonisc** [comment]
Understand. Thought it was a bug.
