### ISSUE TITLE
.DS_STORE

### ISSUE THREAD

**Issue by mehulrao** [EthanRDoesMC/gandalf#46]
We need to remove this file (If it exists) before making the folder into a DEB. The file is inside of the folder that is made before the DEB is packaged

It causes a cydia error

**Comment by EthanRDoesMC** [comment]
While building must be done on a Mac or OS that treats Gandalf.app as a file (new discovery) these files can be disabled from being generated. I'll add that to my growing README documentation. 

My theme setup is done, full time Gandalf again.

**Comment by jonisc** [comment]
@EthanRDoesMC, @mehulrao: does it work correctly now?
1Conan fixed it, I think…

**Comment by EthanRDoesMC** [comment]
is fixed? IDK. Must... update... gandalf!

**Comment by mehulrao** [comment]
Going to close... Will re-open later if it's an issue again
