### ISSUE TITLE
If there are multiple versions of Gandalf "gandalf hold" will probably not work correctly

### ISSUE THREAD

**Issue by jonisc** [EthanRDoesMC/gandalf#53]
*Already working on a solution*

Since @1Conan improved the gandalf script by fetching all packages with `io.github.ethanrdoesmc.gandalf*` currently installed on the device 
and then use the one which is on the top (most likely the one which comes first in the alphabet, but I don't know for sure) the gandalf script might hold the wrong version of gandalf. 
See this line: `PKG_PACKAGE=$(dpkg-query -f '${binary:Package}\n' -W | grep io.github.ethanrdoesmc.gandalf | head -n 1)`
So: there shouldn't be two or more versions of Gandalf installed on one a device. We should make an automated way for adding all other versions of Gandalf to the replaces.txt file or the replaces section in the control file.

**Comment by jonisc** [comment]
#54

**Comment by EthanRDoesMC** [comment]
m okay seems to be done yay
